[gcp_service_account]
type = "service_account"
project_id = "bigquery-demo-436010"
private_key_id = "e24e301ea3b515652ef82d91082ffeee65b0f900"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDHrJ4bxpmeIVIH
EsDQrR2fBFKjUX6OeqBcuWgAm8Bb+DhV7IwA/1YAqwgG92MEITdzuZRPfSg2aiSq
0+cK/UMP19q4z9tPyZA9M9XCVg0RTqkDCVsIT48qnHugnaS7lNt0+PfuL/28Eskv
1VP0Wv39KfslEuJK8pJF2Z3vE57FHReX1ha+/xkgkP+8jvxOy9gj2/9TqU4pl9j6
7OmQZh21jLTsrEutiyBls72F9zSuuNIA834ooehbUQDuaYVEPFjbepiQow23iVo7
obhXuh1oJKkLo5Pp/pnLcidqMZrj/PKr2/d6nzaUlcsP8lCPE8Gw+zlKn2V1LoGF
GLs2M4NrAgMBAAECggEAKtE/yFoCmA+yHNUvJrBwwSg2plHz7w6ps6iIflTn33Dv
d7F1ZkNayGLkokXLZFfRIc5CWPdQN7b0LPOqwEcF6fBSNT5RW58wAIfMh1NXkwYI
pR+M90/ENhF/SzZy3Eyz8LXwyJFe+kUXAlxfF++pNnAZrF4Ly6GPr03Wma1d5wuQ
C3aHtuwAZOyp7Xjmpo4WAtoQZSRcOCBLlM3nrxd5DAHRlVbGyVg1VfB68rbTyHFR
iBwdVI8yDfkq5u6go9Gpg1bEDTqHExX4O/LsRrdvlyrqCMtosNiqrqR944Kt/eEE
u68MLniomE7SK6dHMZJvIo2SwAR7nYlFCfPC+rGKkQKBgQD6TXUH1OkPHuYd9xEY
/Tzf9pnzugVpm999KOsJ2BJMEUSos/UHxnz6zgDXDc0OtSp1fT5V9MfQgShV5zl+
IdDNwyuXejycML8TCiqsTi/0SZiYyHAocFm0Dq+E+Nl92J1v+QJn1QYgjGynWHyL
3d5IbWDFVDtls4L/T+IK0O/TmwKBgQDMOCS5KbhZENTTwsMwWvQj9dfeRlVUSppH
tTw4ZWVQHdJcZ+zrIh7+Uzf/jvwByvBySws2BCu5/+9czBW9n9Ub1LscFXg+gqCA
s/QGCqf3NuSSZ1ViTs1tfw8mlRLmvbxiH+LmOkfeTOHqOiJZuIwyYFg0YKQSX38R
rtZKad0UcQKBgEv5+P0gloG9elI8LZdtPu4ol4CQxZXR95uxMO7zBFLMpw+iWE08
5bDnmP+uM8E0Iqg5FRPYUlKq8chpgF0V/KCIjpHTS9SJQ2aPHnbg4NOBB23Q4aKU
v9XU41g0hSga+WcEqcNEuTBmD5EYXe3CsfdAJDChqcnsHGZNJCruUu3jAoGBAKp6
b8WW20qWr2P7YR/bvZTLZKIsCo1sHbCgzZ2yn0mrK3FyXCfJeyAJ7mRLQ3pnpCN1
G+3Cu5Hw4iuQPtHmPGuYQX5nOdLNDxmBn8LvYFoSG+tPkcqYSAsRF1+48Gdomns7
bRmOK3KasbjrQMOvOHHRVbCbwDuKNrRXRJIoH6MxAoGBAPeTlJ4v2tIBP72qQyWK
9lCbg77A46Iwqn+M3MiD373fROqrmMB24LmnS+8HJQu0g2ItJltJFUtDZ2Dx8iCp
bO6MD3KRJdkxOBw/4IUtEqRdH/IcugX0z9KiEvHgU0zNv/NovCUBZGPoVCJY1VEn
am69roIQzdVFFz6TLUpCPvbq
-----END PRIVATE KEY-----"""
client_email = "bigquery-demo-436010@appspot.gserviceaccount.com"
client_id = "101532584517012335768"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/bigquery-demo-436010%40appspot.gserviceaccount.com"
universe_domain = "googleapis.com"
