[gcp_service_account]
type = "service_account"
project_id = "bigquery-demo-436010"
private_key_id = "099787ddf47154ddcaf802ef7c43081a05059415"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC6rNwl+zsLkjV8
wrkysDZK1yN56TZHNW5murSClwpBbPA5Hat2zKPEnJztraRwTU6aSd+puWSus92x
jfPkgQj2EbJyiukGqv2GiBVfQArX/lXcbT3h6BAFgGM/LV+N5TIdYMP8tqo6aCw9
q6gCibVyzBl4HhELjBbrrT2YDjQqBpzmwzigPSpjMMHSHZXKdwMNGv9JkLLXbLnd
AYnb5Ff7BHpR0xx75RMrHIXfvjmN4PGZ0nr03oExBjvC46wJIzHnV656hlF7cKVJ
H0DyMKRMey8mF+W+D+O544GM0amMYm+ZOfQHrbGgowkWMXftHHeecy/5iMNe6WOu
m7KFsczJAgMBAAECggEAAQskwwy8RIyBeVMj6Xb7/rZkvXKCp88bcPUk8ndd089f
lvol1wRi1tYr3Gf9lx7WXpQAbUr2YJ9Zx9b1F5KzqHrF2KvuQ2fsAncotbY+cCGq
oRCa+708btW507un/E3dMaPZMlb1Eac6/4KvpNJGG8A/VQ7sQVPFFL7n9iskcabU
8FTP/0+vK1/CZGtE4sIS9a3s3ZGSqdeXwM2rbLrQz6XNkxs1u0ms9LojewUk6zYT
bohfS14QTOACnPtswV/kre8f76dqSyyfYBk1uLHMYHRtKjW+fwlKsg1IwQqd1NRT
nLeJh2bnrmzvQmma0vNIgFoPnEelCoIUggZ0uzPAFwKBgQDWb6n1x+nj2FWuUVXC
2M8ga4q+KvsCW0o7iAakDHRGvxkMjDplx6W3cbT38oF2ZiD+K/brJOFQxzud2G9r
9yUtR5HnPQw6qg5UCcRNdz3fKsjd6ON7qgw+2ZsgpiopsSDHo3RS815RYaeuALym
LFOR7sP8lhqKQziwviJubwQzVwKBgQDe27IpjYeY2102BHxxckIDC/T+8KiX/Md8
m49gg9ozv8ILwfQqmhvAEOJxam4RhMo7k4dUstbwXmTnZFz5laghmBK73XMjVU+Q
x/SbZutu2yiGmY5cp82G42Q3JXwDz/c6UoEgpczyaGC/g6hc+EMdvkPdpoizr4un
IukKOscM3wKBgDC7o9aVnlQHoEFDfsgPWdM2XYumXPFGKfKpkUjLA8noOBsf602i
N8ke8E/BLybnQuxAtZbvBL3E6YmP3JKe0jYeI8x3lUXny+XRamlohgknwgqcmMZL
+Qh3j8e1u7NJ6/cy8IbBhFfeZ6slw7nILR3nM2c9/b4aVNHmBBEw7bV1AoGAJTHR
qHHAodhq1Csngd+p+Mw0FaCg4s0Dll54LYmUD3L/teqnD70syH+I65jxyea5wfu7
aH14tiFrAduUUOuTZhf1eHlbUBha8TUONCmXPadCOkTCp+Axw0OMZE/TROeewZMn
jgVeEU8uZohYvzuIKByrQwEaa7LuwfRnpJduxU0CgYAifO7LldwKNVUijK7owLhV
2Q/3moiaP46DAAnToe2LatzMFI0J8ClG999HjuJiPKSBZuFrBh9gpCmdxL8LEWJJ
/ofF6ozAl3Vp/e3j8jVpwdhP5U9KDhYindnaAJtc7eGtCiKFMHcQofPg6IjFGk71
m+iZekKw/Rdhxxm726jdQQ==
-----END PRIVATE KEY-----
"""
client_email = "bigquery-demo-436010@appspot.gserviceaccount.com"
client_id = "101532584517012335768"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/bigquery-demo-436010%40appspot.gserviceaccount.com"
universe_domain = "googleapis.com"
